Create megaman node
Z1wolfmaster1/megameme pull request #10
Opened 2021-05-21 00:43 UTC by Z1wolfmaster1

![create megaman node](https://user-images.githubusercontent.com/28654399/119065561-389d0b00-b9b4-11eb-8265-022299a5cd84.gif)

2021-05-21 17:53 UTC, Manuel-Antunes commented on assets/scripts/actor/megaman/MEGAMAN_STATES.ts
> +// eslint-disable-next-line no-shadow
Pra que isso aqui?

2021-05-21 17:59 UTC, Manuel-Antunes requested changes
favor corrigir os pontos citados

2021-05-21 17:59 UTC, Manuel-Antunes commented on assets/scripts/actor/Actor.ts
> +export default abstract class Actor<S> extends cc.Component {
Gostei do jeito como vc trabalhou esse Actor :3

2021-05-21 17:59 UTC, Manuel-Antunes commented on assets/scripts/actor/megaman/MegamanStateMachine.ts
> +    throw new Error('Method not implemented.');
Apague essas funções aqui que estão sem uso, ou dê um uso a elas

2021-05-21 17:59 UTC, Manuel-Antunes commented on assets/scripts/actor/megaman/Megaman.ts
> +  }
Tá faltando o SET desse state, a propriedade não é readonly, favor inserir.

2021-05-21 20:14 UTC, Manuel-Antunes commented on assets/scripts/actor/megaman/MegamanStateMachine.ts
> +    throw new Error('Method not implemented.');
```suggestion
```

2021-05-21 20:14 UTC, Manuel-Antunes requested changes

2021-05-21 20:14 UTC, Manuel-Antunes commented on assets/scripts/actor/megaman/MegamanStateMachine.ts
> +    throw new Error('Method not implemented.');
```suggestion
```

2021-05-23 05:06 UTC, Manuel-Antunes commented on assets/scripts/actor/megaman/InGameKeyboardController.ts
> +        console.log('apertou');
por favor tente não manter logs no código

2021-05-23 05:07 UTC, Manuel-Antunes commented on assets/scripts/actor/megaman/MEGAMAN_STATES.ts
> +// eslint-disable-next-line no-shadow
?

2021-05-23 05:08 UTC, Manuel-Antunes approved these changes
Mt bem, só dá uma olhadinha nos comentários pfv

2021-05-23 10:12 UTC, Z1wolfmaster1 commented on assets/scripts/actor/megaman/InGameKeyboardController.ts
> +        console.log('apertou');
Eu tô ligado. E não como se o eslint fosse me deixar esquecer.

2021-05-23 10:12 UTC, merged

2021-05-23 12:31 UTC, Z1wolfmaster1 commented on assets/scripts/actor/megaman/MEGAMAN_STATES.ts
> +// eslint-disable-next-line no-shadow
O eslint por algum motivo fica dizendo que esse enum já foi declarado em algum lugar