Create megaman movements
Z1wolfmaster1/megameme pull request #12
Opened 2021-05-26 18:16 UTC by Z1wolfmaster1

2021-05-26 18:20 UTC, Z1wolfmaster1 commented
![create megaman movements](https://user-images.githubusercontent.com/28654399/119711392-e0dc2500-be35-11eb-8d1d-423665124b74.gif)

2021-05-26 22:02 UTC, Manuel-Antunes commented on assets/scripts/actor/PHYSICAL_COLLISION_TAGS.ts
> +enum PHYSICAL_COLLISION_TAGS {
Gostei do jeito como você trabalho as tags de colisão :3

2021-05-26 22:14 UTC, Manuel-Antunes requested changes
Existem alguns problemas de herança, favor corrigi-los e requisitar mais uma vez minha avaliação

2021-05-26 22:14 UTC, Manuel-Antunes commented on assets/scripts/actor/megaman/Megaman.ts
> +  private jumpForce = 26000;
Percebi aqui alguns problemas de herança, favor corrigir esses problemas, são importantes para o seu workflow

2021-05-26 22:14 UTC, Manuel-Antunes commented on assets/scripts/actor/megaman/Megaman.ts
> +  public get isJumping(): boolean {
Esse isJumping poderia estar em uma classe pai tbm

2021-05-26 22:14 UTC, Manuel-Antunes commented on assets/scripts/actor/megaman/Megaman.ts
>    public jump(): void {
Essa função poderia ser criada numa pai, afinal, tem vários personagens que pulam

2021-05-27 12:55 UTC, Manuel-Antunes approved these changes

2021-05-27 14:16 UTC, merged